# Spring Application Configuration
spring.application.name=anticheat-exam-platform

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://prathmeshravekar75_db_user:Prathm%402003@cluster0.77ti55a.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=PRAVP
# Server Configuration
server.port=8080

# Logging Configuration
#logging.level.com.pravp.backend=DEBUG
#logging.level.org.springframework.data.mongodb=DEBUG

# JWT Configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# 24 hours
jwt.expiration=${JWT_EXPIRATION:86400}

# Jackson - serialize dates as ISO strings, not arrays
spring.jackson.serialization.write-dates-as-timestamps=false
